# Schema for the configuration files of the Mobile Number module.

mobile_number.settings:
  type: config_object
  label: 'SMS Framework settings'
  mapping:
    tfa_field:
      type: string
      label: 'TFA User Field'
    verification_secret:
      label: 'Verification Secrete'
      type: string
